-- 清理阅卷中心的孤儿权限点 exam:grading:ai-grade（AI 阅卷）
--
-- 由来：阅卷改为纯人工按题批阅，AI 阅卷路由 POST tasks/:sheetId/ai-grade 及其
-- 服务方法已删除，perms-sync 的 ACTION_LABELS 中 'ai-grade': 'AI 阅卷' 也已移除。
-- 但该权限点此前已被 perms-sync 写进 base_sys_menu，成为无对应接口的孤儿。
--
-- 为什么必须清理：perms-sync（common/perms-sync.service.ts）只有 create 分支，
-- 既不更新也不清理孤儿；MenuService.getTree 无条件返回全部菜单、不校验路由是否存在。
-- 留着会让角色授权树上继续显示「AI 阅卷」这个可勾选项，管理员勾选保存后毫无效果，
-- 误以为系统具备 AI 阅卷能力——而该能力已按需求方要求整体移除。
--
-- 安全性：无路由的权限点是惰性的，不构成可利用面，故此迁移只解决运维误导，不修漏洞。
-- 数据影响：base_sys_role_menu 中指向该菜单的关联行随外键级联删除
-- （见 schema.prisma SysRoleMenu.menu onDelete: Cascade）。该授权本就无接口可调，
-- 删除不会使任何人失去实际能力。
--
-- 按 perms 字符串删除而非按主键：菜单 ID 由各环境自增产生，线上不保证与本地一致，
-- 硬编码 ID 会误删其他模块的权限点。
--
-- ⚠️ 部署顺序：本迁移必须与删除 AI 阅卷路由的代码一同生效，且以代码部署成功为准。
-- perms-sync（bootstrap.service.ts 在每次应用启动时执行）只有 create 分支、不清理孤儿，
-- 因此若迁移已跑而代码回滚到旧镜像（或仍有旧实例重启），旧代码的 @Perms('ai-grade')
-- 会被重新发现，该权限点将原地复活且无任何告警，清理白做。
-- 反向顺序（先部署代码、后跑迁移）只是孤儿权限点多存在一会儿，无害。
-- 重跑本迁移是安全的：DELETE 天然幂等，权限点已复活时再执行即可再次清掉。
DELETE FROM `base_sys_menu` WHERE `perms` = 'exam:grading:ai-grade';
